[sources.chess]
secret_str = "secret_str" # please set me up!

[sources.chess.secret_dict] # please set me up!
key = "value"

[destination.filesystem]
bucket_url = "bucket_url" # please set me up!

[destination.filesystem.credentials]
aws_access_key_id = "aws_access_key_id" # please set me up!
aws_secret_access_key = "aws_secret_access_key" # please set me up!
